disabled_rules: # rule identifiers to exclude from running
  # - colon
  # - comma
  # - control_statement
  # - vertical_whitespace
  # - trailing_whitespace
  # - mark
  - statement_position
  - syntactic_sugar
  - operator_whitespace
  - unused_closure_parameter
  - nesting
  - cyclomatic_complexity
  - line_length
opt_in_rules: # some rules are only opt-in
  - empty_count
  - attributes
  # - closure_end_indentation # kann xcode nicht
  - closure_parameter_position
  # - conditional_returns_on_newline
  - explicit_init
  # - file_header
  - first_where
  # - missing_docs
  # - force_unwrapping
  # - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  # - switch_case_on_newline
  
  # Find all the available rules by running:
  # swiftlint rules
  
#included: # paths to include during linting. `--path` is ignored if present.
#  - Source

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 200
# they can set both implicitly with an array
type_body_length:
  - 600 # warning
  - 1000 # error
# or they can set both explicitly
file_length:
  warning: 1500
  error: 4000
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded:
    - iPhone
    - Dog
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
variable_name:
  excluded:
    - id
function_body_length:
  warning: 500
  error: 1000

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

