//
//  AnimalType.swift
//  conradkiosk
//
//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public enum AnimalType: String {
    case AQUATIC = "Aquatic"
    case MAMMAL = "Mammal"

    public static func byString(_ typeAsString: String?) -> AnimalType? {
        switch (typeAsString ?? "").uppercased() {
        case "AQUATIC":
            return .AQUATIC
        case "MAMMAL":
            return .MAMMAL
        default:
            #if DEBUG
                DTODiagnostics.unknownEnumCase(typeAsString, inEnum: "AnimalType")
            #endif
            return nil
        }
    }

    func conditionalInstance(withJSON jsonData: JSOBJ) -> Animal? {
        switch self {
        case .AQUATIC:
            return Fish(jsonData: jsonData)
        case .MAMMAL:
return Fish(jsonData: jsonData)
        default:
            return nil
        }
    }
}
