//
//  CompanyVerificationRequest.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public struct CompanyVerificationRequest: DefaultRequest, JSOBJSerializable, DictionaryConvertible, CustomStringConvertible {

    // DTO properties:
    public let locale: String?

    public let secToken: String?
    public let txtId: String?

    // Default initializer:
    public init(locale: String?, secToken: String?, txtId: String?) {
        self.locale = locale
        self.secToken = secToken
        self.txtId = txtId
    }

    // Object creation using JSON dictionary representation from NSJSONSerializer:
    public init?(jsonData: JSOBJ?) {
        guard let jsonData = jsonData else { return nil }
        locale = stringFromAny(jsonData["locale"])

        secToken = stringFromAny(jsonData["secToken"])
        txtId = stringFromAny(jsonData["txtId"])

        #if DEBUG
            DTODiagnostics.analize(jsonData: jsonData, expectedKeys: allExpectedKeys, inClassWithName: "CompanyVerificationRequest")
        #endif
    }

    // all expected keys (for diagnostics in debug mode):
    public var allExpectedKeys: Set<String> {
        return Set(["locale", "secToken", "txtId"])
    }

    // dictionary representation (for use with NSJSONSerializer or as parameters for URL request):
    public var jsobjRepresentation: JSOBJ {
        var jsonData = JSOBJ()
        if locale != nil { jsonData["locale"] = locale! }

        if secToken != nil { jsonData["secToken"] = secToken! }
        if txtId != nil { jsonData["txtId"] = txtId! }
        return jsonData
    }

    // printable protocol conformance:
    public var description: String { return "\(jsonString())" }

    // pretty print JSON string representation:
    public func jsonString(paddingPrefix prefix: String = "", printNulls: Bool = false) -> String {
        var returnString = "{\n"

        if let locale = locale { returnString.append("    \(prefix)\"locale\": \"\(locale)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"locale\": null,\n") }

        if let secToken = secToken { returnString.append("    \(prefix)\"secToken\": \"\(secToken)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"secToken\": null,\n") }

        if let txtId = txtId { returnString.append("    \(prefix)\"txtId\": \"\(txtId)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"txtId\": null,\n") }


        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: "\n"))
        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: ","))
        returnString += "\n\(prefix)}"
        return returnString
    }
}