//
//  Company.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public struct Company: JSOBJSerializable, DictionaryConvertible, CustomStringConvertible {

    // DTO properties:
    public let desc: String?
    public let id: Int?
    public let name: String?
    public let website: String?

    // Default initializer:
    public init(desc: String?, id: Int?, name: String?, website: String?) {
        self.desc = desc
        self.id = id
        self.name = name
        self.website = website
    }

    // Object creation using JSON dictionary representation from NSJSONSerializer:
    public init?(jsonData: JSOBJ?) {
        guard let jsonData = jsonData else { return nil }
        desc = stringFromAny(jsonData["desc"])
        id = jsonData["id"] as? Int
        name = stringFromAny(jsonData["name"])
        website = stringFromAny(jsonData["website"])

        #if DEBUG
            DTODiagnostics.analize(jsonData: jsonData, expectedKeys: allExpectedKeys, inClassWithName: "Company")
        #endif
    }

    // all expected keys (for diagnostics in debug mode):
    public var allExpectedKeys: Set<String> {
        return Set(["desc", "id", "name", "website"])
    }

    // dictionary representation (for use with NSJSONSerializer or as parameters for URL request):
    public var jsobjRepresentation: JSOBJ {
        var jsonData = JSOBJ()
        if desc != nil { jsonData["desc"] = desc! }
        if id != nil { jsonData["id"] = id! }
        if name != nil { jsonData["name"] = name! }
        if website != nil { jsonData["website"] = website! }
        return jsonData
    }

    // printable protocol conformance:
    public var description: String { return "\(jsonString())" }

    // pretty print JSON string representation:
    public func jsonString(paddingPrefix prefix: String = "", printNulls: Bool = false) -> String {
        var returnString = "{\n"

        if let desc = desc { returnString.append("    \(prefix)\"desc\": \"\(desc)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"desc\": null,\n") }

        if let id = id { returnString.append("    \(prefix)\"id\": \(id),\n") }
        else if printNulls { returnString.append("    \(prefix)\"id\": null,\n") }

        if let name = name { returnString.append("    \(prefix)\"name\": \"\(name)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"name\": null,\n") }

        if let website = website { returnString.append("    \(prefix)\"website\": \"\(website)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"website\": null,\n") }

        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: "\n"))
        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: ","))
        returnString += "\n\(prefix)}"
        return returnString
    }
}
