//
//  MetaDataRecord.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public struct MetaDataRecord: JSOBJSerializable, DictionaryConvertible, CustomStringConvertible {

    // DTO properties:
    public let key: String?
    public let val: String?

    // Default initializer:
    public init(key: String?, val: String?) {
        self.key = key
        self.val = val
    }

    // Object creation using JSON dictionary representation from NSJSONSerializer:
    public init?(jsonData: JSOBJ?) {
        guard let jsonData = jsonData else { return nil }
        key = stringFromAny(jsonData["key"])
        val = stringFromAny(jsonData["val"])

        #if DEBUG
            DTODiagnostics.analize(jsonData: jsonData, expectedKeys: allExpectedKeys, inClassWithName: "MetaDataRecord")
        #endif
    }

    // all expected keys (for diagnostics in debug mode):
    public var allExpectedKeys: Set<String> {
        return Set(["key", "val"])
    }

    // dictionary representation (for use with NSJSONSerializer or as parameters for URL request):
    public var jsobjRepresentation: JSOBJ {
        var jsonData = JSOBJ()
        if key != nil { jsonData["key"] = key! }
        if val != nil { jsonData["val"] = val! }
        return jsonData
    }

    // printable protocol conformance:
    public var description: String { return "\(jsonString())" }

    // pretty print JSON string representation:
    public func jsonString(paddingPrefix prefix: String = "", printNulls: Bool = false) -> String {
        var returnString = "{\n"

        if let key = key { returnString.append("    \(prefix)\"key\": \"\(key)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"key\": null,\n") }

        if let val = val { returnString.append("    \(prefix)\"val\": \"\(val)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"val\": null,\n") }

        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: "\n"))
        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: ","))
        returnString += "\n\(prefix)}"
        return returnString
    }
}
