//
//  Profile.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public struct Profile: JSOBJSerializable, DictionaryConvertible, CustomStringConvertible {

    // DTO properties:
    public let personalData: PersonalData?
    public let pois: Poi?
    public let statPerTfcModeList: TravelStatisticPerTrafficMode?

    // Default initializer:
    public init(personalData: PersonalData?, pois: Poi?, statPerTfcModeList: TravelStatisticPerTrafficMode?) {
        self.personalData = personalData
        self.pois = pois
        self.statPerTfcModeList = statPerTfcModeList
    }

    // Object creation using JSON dictionary representation from NSJSONSerializer:
    public init?(jsonData: JSOBJ?) {
        guard let jsonData = jsonData else { return nil }
        if let val = PersonalData(jsonData: jsonData["personalData"] as? JSOBJ) { self.personalData = val }
        else { personalData = nil }
        if let val = Poi(jsonData: jsonData["pois"] as? JSOBJ) { self.pois = val }
        else { pois = nil }
        if let val = TravelStatisticPerTrafficMode(jsonData: jsonData["statPerTfcModeList"] as? JSOBJ) { self.statPerTfcModeList = val }
        else { statPerTfcModeList = nil }

        #if DEBUG
            DTODiagnostics.analize(jsonData: jsonData, expectedKeys: allExpectedKeys, inClassWithName: "Profile")
        #endif
    }

    // all expected keys (for diagnostics in debug mode):
    public var allExpectedKeys: Set<String> {
        return Set(["personalData", "pois", "statPerTfcModeList"])
    }

    // dictionary representation (for use with NSJSONSerializer or as parameters for URL request):
    public var jsobjRepresentation: JSOBJ {
        var jsonData = JSOBJ()
        if personalData != nil { jsonData["personalData"] = personalData!.jsobjRepresentation }
        if pois != nil { jsonData["pois"] = pois!.jsobjRepresentation }
        if statPerTfcModeList != nil { jsonData["statPerTfcModeList"] = statPerTfcModeList!.jsobjRepresentation }
        return jsonData
    }

    // printable protocol conformance:
    public var description: String { return "\(jsonString())" }

    // pretty print JSON string representation:
    public func jsonString(paddingPrefix prefix: String = "", printNulls: Bool = false) -> String {
        var returnString = "{\n"

        if let personalData = personalData { returnString.append("    \(prefix)\"personalData\": \("\(personalData.jsonString(paddingPrefix: "\(prefix)    ", printNulls: printNulls))"),\n") }
        else if printNulls { returnString.append("    \(prefix)\"personalData\": null,\n") }

        if let pois = pois { returnString.append("    \(prefix)\"pois\": \("\(pois.jsonString(paddingPrefix: "\(prefix)    ", printNulls: printNulls))"),\n") }
        else if printNulls { returnString.append("    \(prefix)\"pois\": null,\n") }

        if let statPerTfcModeList = statPerTfcModeList { returnString.append("    \(prefix)\"statPerTfcModeList\": \("\(statPerTfcModeList.jsonString(paddingPrefix: "\(prefix)    ", printNulls: printNulls))"),\n") }
        else if printNulls { returnString.append("    \(prefix)\"statPerTfcModeList\": null,\n") }


        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: "\n"))
        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: ","))
        returnString += "\n\(prefix)}"
        return returnString
    }
}