//
//  QuantifiableError.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public struct QuantifiableError: JSOBJSerializable, DictionaryConvertible, CustomStringConvertible {

    // DTO properties:
    public let err: DTOError?
    public let no: Int

    // Default initializer:
    public init(err: DTOError?, no: Int) {
        self.err = err
        self.no = no
    }

    // Object creation using JSON dictionary representation from NSJSONSerializer:
    public init?(jsonData: JSOBJ?) {
        guard let jsonData = jsonData else { return nil }
        if let val = DTOError.byString(jsonData["err"] as? String) { self.err = val }
        else { err = nil }
        guard let val = jsonData["no"] as? Int else { return  nil }
        self.no = val

        #if DEBUG
            DTODiagnostics.analize(jsonData: jsonData, expectedKeys: allExpectedKeys, inClassWithName: "QuantifiableError")
        #endif
    }

    // all expected keys (for diagnostics in debug mode):
    public var allExpectedKeys: Set<String> {
        return Set(["err", "no"])
    }

    // dictionary representation (for use with NSJSONSerializer or as parameters for URL request):
    public var jsobjRepresentation: JSOBJ {
        var jsonData = JSOBJ()
        if err != nil { jsonData["err"] = err!.rawValue }
        jsonData["no"] = no
        return jsonData
    }

    // printable protocol conformance:
    public var description: String { return "\(jsonString())" }

    // pretty print JSON string representation:
    public func jsonString(paddingPrefix prefix: String = "", printNulls: Bool = false) -> String {
        var returnString = "{\n"

        if let err = err { returnString.append("    \(prefix)\"err\": \("\"\(err.rawValue)\""),\n") }
        else if printNulls { returnString.append("    \(prefix)\"err\": null,\n") }
        returnString.append("    \(prefix)\"no\": \(no),\n")

        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: "\n"))
        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: ","))
        returnString += "\n\(prefix)}"
        return returnString
    }
}
