//
//  RegistrationRequest.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public struct RegistrationRequest: DefaultRequest, JSOBJSerializable, DictionaryConvertible, CustomStringConvertible {

    // DTO properties:
    public let locale: String?

    public let pers: Person?
    public let pwd: String?
    public let regKey: String?
    public let secToken: String?

    // Default initializer:
    public init(locale: String?, pers: Person?, pwd: String?, regKey: String?, secToken: String?) {
        self.locale = locale
        self.pers = pers
        self.pwd = pwd
        self.regKey = regKey
        self.secToken = secToken
    }

    // Object creation using JSON dictionary representation from NSJSONSerializer:
    public init?(jsonData: JSOBJ?) {
        guard let jsonData = jsonData else { return nil }
        locale = stringFromAny(jsonData["locale"])

        if let val = PersonalData(jsonData: jsonData["pers"] as? JSOBJ) { self.pers = val }
        else { pers = nil }
        pwd = stringFromAny(jsonData["pwd"])
        regKey = stringFromAny(jsonData["regKey"])
        secToken = stringFromAny(jsonData["secToken"])

        #if DEBUG
            DTODiagnostics.analize(jsonData: jsonData, expectedKeys: allExpectedKeys, inClassWithName: "RegistrationRequest")
        #endif
    }

    // all expected keys (for diagnostics in debug mode):
    public var allExpectedKeys: Set<String> {
        return Set(["locale", "pers", "pwd", "regKey", "secToken"])
    }

    // dictionary representation (for use with NSJSONSerializer or as parameters for URL request):
    public var jsobjRepresentation: JSOBJ {
        var jsonData = JSOBJ()
        if locale != nil { jsonData["locale"] = locale! }

        if pers != nil { jsonData["pers"] = pers!.jsobjRepresentation }
        if pwd != nil { jsonData["pwd"] = pwd! }
        if regKey != nil { jsonData["regKey"] = regKey! }
        if secToken != nil { jsonData["secToken"] = secToken! }
        return jsonData
    }

    // printable protocol conformance:
    public var description: String { return "\(jsonString())" }

    // pretty print JSON string representation:
    public func jsonString(paddingPrefix prefix: String = "", printNulls: Bool = false) -> String {
        var returnString = "{\n"

        if let locale = locale { returnString.append("    \(prefix)\"locale\": \"\(locale)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"locale\": null,\n") }

        if let pers = pers { returnString.append("    \(prefix)\"pers\": \("\(pers.jsonString(paddingPrefix: "\(prefix)    ", printNulls: printNulls))"),\n") }
        else if printNulls { returnString.append("    \(prefix)\"pers\": null,\n") }

        if let pwd = pwd { returnString.append("    \(prefix)\"pwd\": \"\(pwd)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"pwd\": null,\n") }

        if let regKey = regKey { returnString.append("    \(prefix)\"regKey\": \"\(regKey)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"regKey\": null,\n") }

        if let secToken = secToken { returnString.append("    \(prefix)\"secToken\": \"\(secToken)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"secToken\": null,\n") }

        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: "\n"))
        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: ","))
        returnString += "\n\(prefix)}"
        return returnString
    }
}
