//
//  RoleConstant.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public enum RoleConstant: String {
    case MANAGER = "MANAGER"
    case ADMINISTRATOR = "ADMINISTRATOR"

    public static func byString(_ typeAsString: String?) -> RoleConstant? {
        switch (typeAsString ?? "").uppercased() {
        case "MANAGER":
            return .MANAGER
        case "ADMINISTRATOR":
            return .ADMINISTRATOR
        default:
            #if DEBUG
                DTODiagnostics.unknownEnumCase(typeAsString, inEnum: "RoleConstant")
            #endif
            return nil
        }
    }

}
