//
//  sessionRequest.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

open class sessionRequest: defaultRequest {

    // DTO properties:
    public let session: String?

    // Default initializer:
    public init(session: String?) {
        self.session = session
        super.init(locale: "")
    }

    // Object creation using JSON dictionary representation from NSJSONSerializer:
    public required init?(jsonData: JSOBJ?) {
        guard let jsonData = jsonData else { return nil }
        session = stringFromAny(jsonData["session"])

        #if DEBUG
            DTODiagnostics.analize(jsonData: jsonData, expectedKeys: allExpectedKeys, inClassWithName: "sessionRequest")
        #endif
    }

    // all expected keys (for diagnostics in debug mode):
    public override var allExpectedKeys: Set<String> {
        return Set(["session"])
    }

    // dictionary representation (for use with NSJSONSerializer or as parameters for URL request):
    public override
    var jsobjRepresentation: JSOBJ {
        var jsonData = JSOBJ()
        if session != nil { jsonData["session"] = session! }
        return jsonData
    }

    // printable protocol conformance:
    public override var description: String { return "\(jsonString())" }

    // pretty print JSON string representation:
    public override func jsonString(paddingPrefix prefix: String = "", printNulls: Bool = false) -> String {
        var returnString = "{\n"

        if let session = session { returnString.append("    \(prefix)\"session\": \"\(session)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"session\": null,\n") }


        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: "\n"))
        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: ","))
        returnString += "\n\(prefix)}"
        return returnString
    }
}
