//
//  SetSensorDataRequest.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public struct SetSensorDataRequest: SessionRequest, DefaultRequest, JSOBJSerializable, DictionaryConvertible, CustomStringConvertible {

    // DTO properties:
    public let session: String?
    public let locale: String?

    public let accDtList: AcceleratorData?
    public let objId: String?
    public let trkgDtList: TrackingData?

    // Default initializer:
    public init(session: String?, locale: String?, accDtList: AcceleratorData?, objId: String?, trkgDtList: TrackingData?) {
        self.session = session
        self.locale = locale
        self.accDtList = accDtList
        self.objId = objId
        self.trkgDtList = trkgDtList
    }

    // Object creation using JSON dictionary representation from NSJSONSerializer:
    public init?(jsonData: JSOBJ?) {
        guard let jsonData = jsonData else { return nil }
        session = stringFromAny(jsonData["session"])
        locale = stringFromAny(jsonData["locale"])

        if let val = AcceleratorData(jsonData: jsonData["accDtList"] as? JSOBJ) { self.accDtList = val }
        else { accDtList = nil }
        objId = stringFromAny(jsonData["objId"])
        if let val = TrackingData(jsonData: jsonData["trkgDtList"] as? JSOBJ) { self.trkgDtList = val }
        else { trkgDtList = nil }

        #if DEBUG
            DTODiagnostics.analize(jsonData: jsonData, expectedKeys: allExpectedKeys, inClassWithName: "SetSensorDataRequest")
        #endif
    }

    // all expected keys (for diagnostics in debug mode):
    public var allExpectedKeys: Set<String> {
        return Set(["session", "locale", "accDtList", "objId", "trkgDtList"])
    }

    // dictionary representation (for use with NSJSONSerializer or as parameters for URL request):
    public var jsobjRepresentation: JSOBJ {
        var jsonData = JSOBJ()
        if session != nil { jsonData["session"] = session! }
        if locale != nil { jsonData["locale"] = locale! }

        if accDtList != nil { jsonData["accDtList"] = accDtList!.jsobjRepresentation }
        if objId != nil { jsonData["objId"] = objId! }
        if trkgDtList != nil { jsonData["trkgDtList"] = trkgDtList!.jsobjRepresentation }
        return jsonData
    }

    // printable protocol conformance:
    public var description: String { return "\(jsonString())" }

    // pretty print JSON string representation:
    public func jsonString(paddingPrefix prefix: String = "", printNulls: Bool = false) -> String {
        var returnString = "{\n"

        if let session = session { returnString.append("    \(prefix)\"session\": \"\(session)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"session\": null,\n") }

        if let locale = locale { returnString.append("    \(prefix)\"locale\": \"\(locale)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"locale\": null,\n") }

        if let accDtList = accDtList { returnString.append("    \(prefix)\"accDtList\": \("\(accDtList.jsonString(paddingPrefix: "\(prefix)    ", printNulls: printNulls))"),\n") }
        else if printNulls { returnString.append("    \(prefix)\"accDtList\": null,\n") }

        if let objId = objId { returnString.append("    \(prefix)\"objId\": \"\(objId)\",\n") }
        else if printNulls { returnString.append("    \(prefix)\"objId\": null,\n") }

        if let trkgDtList = trkgDtList { returnString.append("    \(prefix)\"trkgDtList\": \("\(trkgDtList.jsonString(paddingPrefix: "\(prefix)    ", printNulls: printNulls))"),\n") }
        else if printNulls { returnString.append("    \(prefix)\"trkgDtList\": null,\n") }

        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: "\n"))
        returnString = returnString.trimmingCharacters(in: CharacterSet(charactersIn: ","))
        returnString += "\n\(prefix)}"
        return returnString
    }
}
