//
//  TrackingAction.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public enum TrackingAction: String {
    case START
    case PAUSE
    case STOP

    public static func byString(_ typeAsString: String?) -> TrackingAction? {
        switch (typeAsString ?? "").uppercased() {
        case "START":
            return .START
        case "PAUSE":
            return .PAUSE
        case "STOP":
            return .STOP
        default:
            #if DEBUG
                DTODiagnostics.unknownEnumCase(typeAsString, inEnum: "TrackingAction")
            #endif
            return nil
        }
    }

}
