//
//  TrafficModeConstant.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public enum TrafficModeConstant: String {
    case CAR
    case BICYCLE
    case WALK
    case PUBLIC_TRANSPORT
    case UNKNOWN

    public static func byString(_ typeAsString: String?) -> TrafficModeConstant? {
        switch (typeAsString ?? "").uppercased() {
        case "CAR":
            return .CAR
        case "BICYCLE":
            return .BICYCLE
        case "WALK":
            return .WALK
        case "PUBLIC_TRANSPORT":
            return .PUBLIC_TRANSPORT
        case "UNKNOWN":
            return .UNKNOWN
        default:
            #if DEBUG
                DTODiagnostics.unknownEnumCase(typeAsString, inEnum: "TrafficModeConstant")
            #endif
            return nil
        }
    }

}