//
//  TravelStatistic.swift

//  Automatically created by SwiftDTO.
//  Copyright (c) 2016 Farbflash. All rights reserved.

// DO NOT EDIT THIS FILE!
// This file was automatically generated from a xcmodel file (CoreData XML Scheme)
// Edit the source coredata model (in the CoreData editor) and then use the SwiftDTO
// to create the corresponding DTO source files automatically

import Foundation

public protocol TravelStatistic: DictionaryConvertible {
    var no: Int? { get }
    var travelTime: Int? { get }
    var travelledDist: Int? { get }
}
